position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ns1_panda_joint1
    - ns1_panda_joint2
    - ns1_panda_joint3
    - ns1_panda_joint4
    - ns1_panda_joint5
    - ns1_panda_joint6
    - ns1_panda_joint7
  constraints:
    goal_time: 0.5
    ns1_panda_joint1:
      goal: 0.05
    ns1_panda_joint2:
      goal: 0.05
    ns1_panda_joint3:
      goal: 0.05
    ns1_panda_joint4:
      goal: 0.05
    ns1_panda_joint5:
      goal: 0.05
    ns1_panda_joint6:
      goal: 0.05
    ns1_panda_joint7:
      goal: 0.05

franka_state_controller:
  type: franka_control/FrankaStateController
  publish_rate: 30  # [Hz]
  joint_names:
    - ns1_panda_joint1
    - ns1_panda_joint2
    - ns1_panda_joint3
    - ns1_panda_joint4
    - ns1_panda_joint5
    - ns1_panda_joint6
    - ns1_panda_joint7
  arm_id: ns1_panda
