global_frame: ns2_odom
rolling_window: true
robot_base_frame: ns2_base_link

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
